version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
