version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: blog_db
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - blog-db:/var/lib/mysql

volumes:
  blog-db:
